### ISSUE TITLE
crDroid-10.0 v2023.12.23 random reboots

### ISSUE THREAD

**Issue by jaefferson** [naz664/crDroid_patches#58]
My device is having several reboots every day at random time intervals.
Device: Asus ZenFone Max Pro M2 (ZB631KL)
Codename: ASUS_X01BDA | ASUS_X01BD_1
RAM/Internal memory: 6GB/64GB
Chipset: Snapdragon 660 Qualcomm SDM660
GPU: Adreno 512

**Comment by grothedev** [comment]
having the same issue. 
here's my log:

```
--------- switch to kernel
[32m[ 01-16 20:38:09.507     1:    1 I/(5)[1:init] ]
processing action (sys.rss_hwm_reset.on=1) from (/system/etc/init/rss_hwm_reset.rc:24)[0m

[32m[ 01-16 20:38:09.507     1:    1 I/(5)[1:init] ]
starting service 'rss_hwm_reset'...[0m

[33m[ 01-16 20:38:09.509     1:    1 W/(5)[1:init]libprocessgroup ]
SetCgroup::ExecuteForProcess: failed to open /dev/blkio//cgroup.procs: No such file or directory[0m

[33m[ 01-16 20:38:09.509     1:    1 W/(5)[1:init]libprocessgroup ]
Failed to apply NormalIoPriority process profile[0m

--------- switch to crash
[31m[ 01-16 20:38:09.507  4606: 4726 E/AndroidRuntime ]
*** FATAL EXCEPTION IN SYSTEM PROCESS: android.net.connectivity.com.android.modules.utils.BackgroundThread
java.lang.NullPointerException: Attempt to invoke interface method 'void android.net.connectivity.com.android.net.module.util.IBpfMap.forEach(android.net.connectivity.com.android.net.module.util.IBpfMap$ThrowingBiConsumer)' on a null object reference
	at android.net.connectivity.com.android.server.BpfNetMaps.getMapSize(BpfNetMaps.java:1010)
	at android.net.connectivity.com.android.server.BpfNetMaps.pullBpfMapInfoAtom(BpfNetMaps.java:1023)
	at android.net.connectivity.com.android.server.BpfNetMaps$$ExternalSyntheticLambda3.onPullAtom(R8$$SyntheticClass:0)
	at android.app.StatsManager$PullAtomCallbackInternal.lambda$onPullAtom$0(StatsManager.java:688)
	at android.app.StatsManager$PullAtomCallbackInternal.$r8$lambda$wkAbOHvoKcxNXFVeEyQU5e9coiY(Unknown Source:0)
	at android.app.StatsManager$PullAtomCallbackInternal$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

device: unihertz jelly 2
